name: Codespace Keepalive
on:
  schedule:
    - cron: "0 12 */5 * *"
  workflow_dispatch: {}
permissions:
  contents: write
  codespaces: write
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Wake Codespace
        run: gh codespace start cuddly-space-orbit-5v6554x69rqc7969
        env:
          GH_TOKEN: ${{ secrets.CODESPACE_PAT }}
